<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType Condition="'$(Configuration)' == 'Debug'">Exe</OutputType>
    <OutputType Condition="'$(Configuration)' != 'Debug'">WinExe</OutputType>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <ServerGarbageCollection>false</ServerGarbageCollection>
    <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
    <InvariantGlobalization>true</InvariantGlobalization>
    <TieredPGO>false</TieredPGO>

    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>false</PublishTrimmed>
    <Optimize>true</Optimize>
    <ApplicationIcon>canopy.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Canopy.Core\Canopy.Core.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="H.NotifyIcon" Version="2.5.0-dev.2"/>
    <PackageReference Include="SynesthesiaDev.Chibi.Core" Version="2026.619.1"/>
    <PackageReference Include="System.Drawing.Common" Version="11.0.0-preview.6.26359.118"/>
    <PackageReference Include="Vanara.PInvoke.User32" Version="5.0.5"/>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="canopy.ico" />
  </ItemGroup>

</Project>
